### PR TITLE
Monzt0r edition

### PR DESCRIPTION
**Pull request by CryptoMonzt0r**
Updated Temps on some miners to try help prevent overheat if left for to long or errors !

### CODE REVIEW

**Comment by MikeBuzz** [comment]
Nice, but maybe it would be better to have the temp set in the config file

**Comment by CryptoMonzt0r** [comment]
Would be a better option but I do not have the skills to implement it that way if you can find a better way that would be great as I was unlucky on the silicon lottery I have to set it to 80 degrees and it would help other new miners from burning out there cards if they are in the same situation or just as a failsafe.

**Comment by tutulino** [comment]
Can be implemented on config, but what is advantage os control temps this way?, I think is easier control on Afterburner.

**Comment by CryptoMonzt0r** [comment]
For new users who have no idea that they could cook there cards or for people who have had bad luck on hardware and have to run at 50% power limit or the cards overheat even with adequate tower cooling etc.
Also in case error occurs and cards overheat whilst you are away or asleep I find it a good failsafe just wish could use it on Klaus as that is my main culprit for overheats.

**Comment by tutulino** [comment]
Sorry, I think temps are easier to control outside app with software specific like afterburner

**Pull request closed without merging**
